docker:
  registry: docker.io
  repoName: os-alpine


tags:
  core:
    apk:
    pip:
  docker:
    apk:
      - docker
    pip:
  build:
    apk:
      - build-base
      - coreutils
      - zip
      - curl
      - jemalloc-dev
      - linux-headers
      - cmake
      - ca-certificates
      - bash
      - tcl
      - jq
      - py-pip
    pip:
      - yq
