docker:
  registry: docker.io
  repoName: os-alpine


tags:
  core:
    packages:
  docker:
    packages:
      - docker
  build:
    packages:
      - build-base
      - coreutils
      - zip
      - curl
      - jemalloc-dev
      - linux-headers
      - cmake
      - ca-certificates
      - bash
      - tcl
